/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AlcoholTime } from './models/AlcoholTime';
export type { ApiException } from './models/ApiException';
export type { ApiKeyParameters } from './models/ApiKeyParameters';
export type { ArtificialBeatGeneratorParams } from './models/ArtificialBeatGeneratorParams';
export type { AudioCreateParams } from './models/AudioCreateParams';
export type { AudioResponse } from './models/AudioResponse';
export type { BaseLightsEffectCreateParams } from './models/BaseLightsEffectCreateParams';
export type { BasePoster } from './models/BasePoster';
export { BeatFadeOutCreateParams } from './models/BeatFadeOutCreateParams';
export type { BeatFadeOutProps } from './models/BeatFadeOutProps';
export type { CenturionParams } from './models/CenturionParams';
export type { CenturionResponse } from './models/CenturionResponse';
export type { CreateSceneParams } from './models/CreateSceneParams';
export type { ErrorPoster } from './models/ErrorPoster';
export type { FieldErrors } from './models/FieldErrors';
export { FooterSize } from './models/FooterSize';
export type { GEWISPhotoAlbumParams } from './models/GEWISPhotoAlbumParams';
export type { GroupFixtureOverrideParams } from './models/GroupFixtureOverrideParams';
export type { HandlerResponse_AudioResponse_ } from './models/HandlerResponse_AudioResponse_';
export type { HandlerResponse_LightsGroupResponse_ } from './models/HandlerResponse_LightsGroupResponse_';
export type { HandlerResponse_ScreenResponse_ } from './models/HandlerResponse_ScreenResponse_';
export type { HornData } from './models/HornData';
export { HornEvent } from './models/HornEvent';
export type { Information } from './models/Information';
export type { InformationParams } from './models/InformationParams';
export type { LightsColorResponse } from './models/LightsColorResponse';
export type { LightsControllerCreateParams } from './models/LightsControllerCreateParams';
export type { LightsControllerResponse } from './models/LightsControllerResponse';
export type { LightsEffectsColorCreateParams } from './models/LightsEffectsColorCreateParams';
export type { LightsEffectsMovementCreateParams } from './models/LightsEffectsMovementCreateParams';
export type { LightsGroupCreateParams } from './models/LightsGroupCreateParams';
export type { LightsGroupResponse } from './models/LightsGroupResponse';
export type { LightsInGroup } from './models/LightsInGroup';
export type { LightsMovingHeadRgbCreateParams } from './models/LightsMovingHeadRgbCreateParams';
export type { LightsMovingHeadWheelCreateParams } from './models/LightsMovingHeadWheelCreateParams';
export type { LightsParCreateParams } from './models/LightsParCreateParams';
export type { LightsSceneFixtureResponse } from './models/LightsSceneFixtureResponse';
export type { LightsSceneResponse } from './models/LightsSceneResponse';
export type { LocalPoster } from './models/LocalPoster';
export type { LocalPosterType } from './models/LocalPosterType';
export type { MediaPoster } from './models/MediaPoster';
export type { Message } from './models/Message';
export type { MessageParams } from './models/MessageParams';
export type { MixTapeResponse } from './models/MixTapeResponse';
export type { MovingHeadRgbResponse } from './models/MovingHeadRgbResponse';
export type { MovingHeadWheelResponse } from './models/MovingHeadWheelResponse';
export type { NewHandlerParams } from './models/NewHandlerParams';
export type { OidcConfig } from './models/OidcConfig';
export type { OidcParameters } from './models/OidcParameters';
export type { ParResponse } from './models/ParResponse';
export type { Partial_MessageParams_ } from './models/Partial_MessageParams_';
export type { Partial_Record_SocketioNamespaces_string__ } from './models/Partial_Record_SocketioNamespaces_string__';
export type { PhotoPoster } from './models/PhotoPoster';
export type { PhotoResponse } from './models/PhotoResponse';
export type { Poster } from './models/Poster';
export { PosterType_AGENDA } from './models/PosterType_AGENDA';
export { PosterType_ERROR } from './models/PosterType_ERROR';
export { PosterType_EXTERNAL } from './models/PosterType_EXTERNAL';
export { PosterType_IMAGE } from './models/PosterType_IMAGE';
export { PosterType_INFIMA } from './models/PosterType_INFIMA';
export { PosterType_LOGO } from './models/PosterType_LOGO';
export { PosterType_PHOTO } from './models/PosterType_PHOTO';
export { PosterType_TRAINS } from './models/PosterType_TRAINS';
export { PosterType_UNKNOWN } from './models/PosterType_UNKNOWN';
export { PosterType_VIDEO } from './models/PosterType_VIDEO';
export { RandomPositionCreateParams } from './models/RandomPositionCreateParams';
export type { RandomPositionProps } from './models/RandomPositionProps';
export { RgbColor } from './models/RgbColor';
export type { RgbColorDefinition } from './models/RgbColorDefinition';
export type { RgbColorSpecification } from './models/RgbColorSpecification';
export { RoomStatus } from './models/RoomStatus';
export type { SceneFixtureParams } from './models/SceneFixtureParams';
export type { ScreenCreateParams } from './models/ScreenCreateParams';
export type { ScreenResponse } from './models/ScreenResponse';
export { SearchLightCreateParams } from './models/SearchLightCreateParams';
export type { SearchLightProps } from './models/SearchLightProps';
export type { SetAudioPlayingParams } from './models/SetAudioPlayingParams';
export { SingleFloodCreateParams } from './models/SingleFloodCreateParams';
export type { SingleFloodProps } from './models/SingleFloodProps';
export type { SkipCenturionRequest } from './models/SkipCenturionRequest';
export type { SongData } from './models/SongData';
export { SongEvent } from './models/SongEvent';
export { SparkleCreateParams } from './models/SparkleCreateParams';
export type { SparkleProps } from './models/SparkleProps';
export type { SpotifyUserResponse } from './models/SpotifyUserResponse';
export { StaticColorCreateParams } from './models/StaticColorCreateParams';
export type { StaticColorProps } from './models/StaticColorProps';
export { StrobeCreateParams } from './models/StrobeCreateParams';
export type { StrobeProps } from './models/StrobeProps';
export { TableRotateCreateParams } from './models/TableRotateCreateParams';
export type { TableRotateProps } from './models/TableRotateProps';
export type { TrackChangeEvent } from './models/TrackChangeEvent';
export type { TrainResponse } from './models/TrainResponse';
export type { User } from './models/User';
export type { UserProfile } from './models/UserProfile';
export type { ValidateError } from './models/ValidateError';
export { WaveCreateParams } from './models/WaveCreateParams';
export type { WaveProps } from './models/WaveProps';
export { WheelColor } from './models/WheelColor';

export { ArtificialBeatGeneratorService } from './services/ArtificialBeatGeneratorService';
export { AudiosService } from './services/AudiosService';
export { AuthenticationService } from './services/AuthenticationService';
export { HandlersService } from './services/HandlersService';
export { InfoscreenService } from './services/InfoscreenService';
export { LightsService } from './services/LightsService';
export { ModesService } from './services/ModesService';
export { PosterScreenService } from './services/PosterScreenService';
export { ScreensService } from './services/ScreensService';
export { SpotifyService } from './services/SpotifyService';
export { UserService } from './services/UserService';
