name: Lint and build

on:
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:
  generate-client-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v4
        with:
          repository: gewis/aurora-core
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Run tsoa
        uses: borales/actions-yarn@v5
        with:
          cmd: tsoa

      - name: Generate client
        uses: borales/actions-yarn@v5
        with:
          cmd: gen-client-backoffice

      - name: Copy client
        run: cp -r ../aurora-backoffice/src/api/ ./api

      - uses: actions/upload-artifact@v4
        with:
          name: api-client
          path: api

  build-and-lint:
    needs:
      generate-client-files
    uses: GEWIS/actions/.github/workflows/typescript-lint-and-build.yml@v0.0.2
    with:
      node-version: "22.x"
      package-manager: "yarn"
      artifact-name: "api-client"
      artifact-path: "src/api"
      lint: true
      format: true
      build: true
